### ISSUE TITLE
List content overflows viewport

### ISSUE THREAD

**Issue by sven1103** [qbicsoftware/qbic_presentations#1]
Hey Julian, 
in your continous integration presentation, one vertical slide is not rendered properly:

<code html>
<section>
                        <div>
                            <h3>Benefits of CI </h3> <img style="float:right; width=20%" src="figs/thumb_up.jpg"/>
                        </div>
                        <ul>
                            <li> Automatization </li>
                                <ul>
                                    <li>Minimize the manual tasks </li>
                                    <li>Consistency in build and deploy</li>
                                </ul>
                            <li>Workflows between environments</li>
                                <ul>
                                    <li>Development - Testing- Production</li>
                                </ul>   
                            <li>Enables continous delivery</li>
                        </ul>
                    </section>
</code>

The list content is cut of:

![image](https://user-images.githubusercontent.com/9976560/31306672-04a45478-ab55-11e7-977a-99bf3f07a204.png)

**Comment by sven1103** [comment]
try to put the ```<ul></ul>``` part within a ```<div></div>```

**Comment by sven1103** [comment]
![image](https://user-images.githubusercontent.com/9976560/31306748-99210488-ab56-11e7-8a7d-9c3993e537f1.png)

**Comment by julianspaeth** [comment]
Danke Sven :)
